#!/usr/bin/env node
/* Turns a directory of per-site stats into the two files a person reads.

   Usage:  node analysis/report.js --in stats/ --out analysis/
*/
'use strict';
const fs = require('fs');
const path = require('path');

function arg(name, dflt) {
  const i = process.argv.indexOf('--' + name);
  if (i < 0 || i + 1 >= process.argv.length) {
    if (dflt !== undefined) return dflt;
    console.error('missing --' + name); process.exit(1);
  }
  return process.argv[i + 1];
}

const IN = arg('in'), OUT = arg('out', path.join(__dirname));
const all = fs.readdirSync(IN).filter(f => f.endsWith('.json')).sort()
  .map(f => JSON.parse(fs.readFileSync(path.join(IN, f), 'utf8')))
  .filter(s => s && s.site && s.os);
if (!all.length) { console.error('no site stats in ' + IN); process.exit(1); }

/* A reference site was chosen by a person, so it cannot be part of a number
   that claims to be a random sample. It gets measured the same way and then
   held up against the draw. */
let refs = all.filter(s => s.site.reference);
let sites = all.filter(s => !s.site.reference);
if (!sites.length) { sites = all; refs = []; }

const pct = v => (v == null ? '' : (100 * v).toFixed(0) + '%');
const num = v => (v == null ? '' : String(v).replace(/\B(?=(\d{3})+(?!\d))/g, ','));
const sum = f => sites.reduce((t, s) => t + (f(s) || 0), 0);
const median = v => { const s = v.slice().sort((a, b) => a - b); return s.length ? s[Math.floor(s.length / 2)] : 0; };

const osArea = sum(s => s.os.area), osmArea = sum(s => s.osm.area);
const osCount = sum(s => s.os.count), osmCount = sum(s => s.osm.count);
const missCount = sum(s => s.missing.count), missArea = sum(s => s.missing.area);
const houses = sum(s => s.missing.housesized);
const totals = {
  sites: sites.length,
  osCount, osmCount, osArea, osmArea, missCount, missArea, houses,
  extraCount: sum(s => s.extra.count),
  missingShare: osCount ? missCount / osCount : 0,
  missingAreaShare: osArea ? missArea / osArea : 0,
  areaRatio: osArea ? osmArea / osArea : 0,
  medianSiteMissing: median(sites.map(s => s.missingShare || 0)),
  worst: sites.slice().sort((a, b) => (b.missingShare || 0) - (a.missingShare || 0))[0],
  best: sites.slice().sort((a, b) => (a.missingShare || 0) - (b.missingShare || 0))[0],
  complete: sites.filter(s => (s.missingShare || 0) < 0.10).length,
  half: sites.filter(s => (s.missingShare || 0) >= 0.50).length
};

/* ---- CSV: one row per site, for anyone who wants to check the working ---- */
const head = ['postcode', 'district', 'region', 'grid_square', 'lat', 'lon',
  'os_footprints', 'osm_footprints', 'os_area_m2', 'osm_area_m2',
  'missing_footprints', 'missing_area_m2', 'missing_share', 'missing_area_share',
  'missing_outbuilding', 'missing_housesized', 'missing_large', 'osm_only_footprints', 'chosen_not_drawn'];
const rows = all.map(s => [
  s.site.postcode, s.site.district, s.site.region, s.site.square, s.site.lat, s.site.lon,
  s.os.count, s.osm.count, s.os.area, s.osm.area,
  s.missing.count, s.missing.area, s.missingShare, s.missingAreaShare,
  s.missing.outbuilding, s.missing.housesized, s.missing.large, s.extra.count,
  s.site.reference ? 'yes' : ''
].map(v => {
  const t = String(v == null ? '' : v);
  return /[",]/.test(t) ? '"' + t.replace(/"/g, '""') + '"' : t;
}).join(','));
fs.writeFileSync(path.join(OUT, 'coverage.csv'), head.join(',') + '\n' + rows.join('\n') + '\n');

/* ---- the readable version ---- */
const byMissing = all.slice().sort((a, b) => (b.missingShare || 0) - (a.missingShare || 0));
const L = [];
L.push('# How much is OpenStreetMap missing?');
L.push('');
L.push('Generated by `.github/workflows/coverage-audit.yml` on ' + new Date().toISOString().slice(0, 10) +
  '. Every number below was measured, not estimated: Ordnance Survey OpenMap Local against live');
L.push('OpenStreetMap, in the same box, matched polygon to polygon. Rebuild it from the Actions tab');
L.push('to get a fresh draw.');
L.push('');
L.push('## The answer');
L.push('');
L.push('Across **' + totals.sites + ' place' + (totals.sites === 1 ? '' : 's') +
  '** drawn at random from Great Britain:');
L.push('');
L.push('| | |');
L.push('|---|---|');
L.push('| Buildings Ordnance Survey has | **' + num(osCount) + '** |');
L.push('| Buildings OpenStreetMap has | **' + num(osmCount) + '** |');
L.push('| OS footprints with nothing from OSM on them | **' + num(missCount) + '** — ' + pct(totals.missingShare) + ' of every building measured |');
L.push('| …of those, house-sized (50–400 m²) | **' + num(houses) + '** |');
L.push('| Share of OS floor area OSM does not have | **' + pct(totals.missingAreaShare) + '** |');
L.push('| Buildings OSM has that OS does not | ' + num(totals.extraCount) + ' |');
L.push('');
L.push('In a **typical place**, though, **' + pct(totals.medianSiteMissing) + '** of the buildings are missing.');
L.push('');
L.push('Those two numbers are both true and they are not the same measurement. The first');
L.push('pools every building in the sample, so it is dominated by the cities, which hold most');
L.push('of the buildings and are mapped best. The second is the middle place, which is where');
L.push('most of Great Britain by area actually is. Cities are close to finished; everywhere');
L.push('else is not.');
L.push('');
L.push('Places essentially complete (under 10% missing): **' + totals.complete + ' of ' + totals.sites + '**. ' +
  'Places missing half or more: **' + totals.half + ' of ' + totals.sites + '**.');
L.push('');
if (totals.sites > 1 && totals.worst && totals.best) {
  L.push('- Worst: **' + totals.worst.site.postcode + '**, ' + totals.worst.site.district +
    ' — ' + pct(totals.worst.missingShare) + ' missing (' + num(totals.worst.missing.count) + ' footprints)');
  L.push('- Best: **' + totals.best.site.postcode + '**, ' + totals.best.site.district +
    ' — ' + pct(totals.best.missingShare) + ' missing');
  L.push('');
}
/* ---- the question that started this ---- */
if (refs.length) {
  L.push('## The place this started with');
  L.push('');
  for (const r of refs) {
    const share = r.missingShare || 0;
    const below = sites.filter(s => (s.missingShare || 0) < share).length;
    const rank = sites.length ? Math.round(100 * below / sites.length) : null;
    L.push('**' + r.site.postcode + '** — ' + r.site.district + ', ' + r.site.region);
    L.push('');
    L.push('| | |');
    L.push('|---|---|');
    L.push('| Buildings Ordnance Survey has | **' + num(r.os.count) + '** |');
    L.push('| Buildings OpenStreetMap has | **' + num(r.osm.count) + '** |');
    L.push('| Missing from OpenStreetMap | **' + num(r.missing.count) + '** (' + pct(share) + ') |');
    L.push('| …house-sized | **' + num(r.missing.housesized) + '** |');
    L.push('| The random sample, for comparison | ' + pct(totals.medianSiteMissing) + ' missing at the median place |');
    L.push('');
    if (rank != null && sites.length >= 5) {
      const verdict = rank >= 90
        ? 'unusually badly mapped — worse than nearly every place drawn. Even so, the gap is ' +
          'the same kind as everywhere else, only larger'
        : rank >= 65
          ? 'worse mapped than most places, but well inside the range the rest of the country shows'
          : rank <= 25
            ? 'better mapped than most of Great Britain'
            : 'ordinary — the gap here is the gap almost everywhere';
      L.push('It is worse than **' + rank + '%** of the places drawn at random. That makes it ' +
        verdict + '.');
      L.push('');
      L.push(share > totals.medianSiteMissing
        ? 'So: not a blindspot. A normal amount of missing, at a place where there was a lot to miss.'
        : 'So: not a blindspot, and not even a bad one by national standards.');
      L.push('');
    }
  }
}

L.push('## Every place measured');
L.push('');
L.push('Sorted worst first. "Missing" is an OS building with no OpenStreetMap building anywhere on it.' +
  (refs.length ? ' A * marks a place chosen rather than drawn — it is not in the totals above.' : ''));
L.push('');
L.push('| Place | District | OS | OSM | Missing | % missing | House-sized | OSM-only |');
L.push('|---|---|---:|---:|---:|---:|---:|---:|');
for (const s of byMissing) {
  L.push('| ' + s.site.postcode + (s.site.reference ? ' *' : '') + ' | ' + s.site.district + ' | ' + num(s.os.count) + ' | ' + num(s.osm.count) +
    ' | ' + num(s.missing.count) + ' | ' + pct(s.missingShare) + ' | ' + num(s.missing.housesized) +
    ' | ' + num(s.extra.count) + ' |');
}
L.push('');
L.push('## How to read this');
L.push('');
L.push('- **Missing** counts OS footprints that no OpenStreetMap building overlaps. It is not');
L.push('  "OS has more polygons than OSM": OS draws a terrace of eight houses as one block and');
L.push('  OSM often draws all eight, so counts alone would be nonsense in both directions. Each');
L.push('  footprint is matched to the other dataset by position before anything is counted.');
L.push('- **OSM-only** is the honest other half. Some of it is new build finished after the OS');
L.push('  release; some is sheds and canopies OS does not survey. It is not error on OSM\'s part,');
L.push('  and this audit does not treat it as such.');
L.push('- **House-sized** is footprint area between 50 and 400 m², which is a dwelling nearly');
L.push('  every time. It is the closest this data comes to counting missing houses, and it will');
L.push('  undercount flats — one block of flats is one large footprint, not forty houses.');
L.push('- OS OpenMap Local is Great Britain only, so Northern Ireland is not in this sample.');
L.push('');
L.push('Contains OS data © Crown copyright and database right. Open Government Licence v3.');
L.push('Contains OpenStreetMap data © OpenStreetMap contributors, Open Database Licence.');
L.push('');
fs.writeFileSync(path.join(OUT, 'coverage.md'), L.join('\n'));
fs.writeFileSync(path.join(OUT, 'coverage.json'),
  JSON.stringify({ totals: totals, sites: sites, reference: refs }, null, 1));

console.error(totals.sites + ' sites: ' + num(missCount) + ' of ' + num(osCount) + ' OS footprints missing from OSM (' +
  pct(totals.missingShare) + '), median site ' + pct(totals.medianSiteMissing));
